// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVn0ybRsYCrAx_orue4UN_Le7O1TzO2JA',
    appId: '1:743881940512:web:44103db023e083f1e5e645',
    messagingSenderId: '743881940512',
    projectId: 'growmind-8d0b6',
    authDomain: 'growmind-8d0b6.firebaseapp.com',
    storageBucket: 'growmind-8d0b6.firebasestorage.app',
    measurementId: 'G-130Q8WKMJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-3W06Wkup6dNLFSXoBjHDY3QNvBYzEzQ',
    appId: '1:743881940512:android:558356651bbd5525e5e645',
    messagingSenderId: '743881940512',
    projectId: 'growmind-8d0b6',
    storageBucket: 'growmind-8d0b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr6LZG4hLtFxGKVM9xLHezEl_f7a7ySsE',
    appId: '1:743881940512:ios:dda682ab3774f18de5e645',
    messagingSenderId: '743881940512',
    projectId: 'growmind-8d0b6',
    storageBucket: 'growmind-8d0b6.firebasestorage.app',
    iosBundleId: 'com.example.growmind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr6LZG4hLtFxGKVM9xLHezEl_f7a7ySsE',
    appId: '1:743881940512:ios:dda682ab3774f18de5e645',
    messagingSenderId: '743881940512',
    projectId: 'growmind-8d0b6',
    storageBucket: 'growmind-8d0b6.firebasestorage.app',
    iosBundleId: 'com.example.growmind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVn0ybRsYCrAx_orue4UN_Le7O1TzO2JA',
    appId: '1:743881940512:web:d92ab85ddccb7949e5e645',
    messagingSenderId: '743881940512',
    projectId: 'growmind-8d0b6',
    authDomain: 'growmind-8d0b6.firebaseapp.com',
    storageBucket: 'growmind-8d0b6.firebasestorage.app',
    measurementId: 'G-TVBBX6LXZR',
  );
}
